version: "3"

services:
  recebecep:
    container_name: recebe-cep
    build:
      context: ./recebecep
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
    networks:
      - local-network

  temperaturacep:
    container_name: temp-cep
    build:
      context: ./temperaturacep
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - zipkin
    networks:
      - local-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge